export const works = [
  {
    category: 'Branding',
    title: 'EMPHERIA AGRICULTURE',
    href: '/projects',
    imageSrc: '/images/empheria.jpg',
    imageAlt: 'Empheria Agriculture',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#1a2a3a]',
  },
  {
    category: 'Mobile App Design',
    title: 'NEOBANKING MOBILE APP',
    href: '/projects',
    imageSrc: '/images/bankingapp.png',
    imageAlt: 'Neobanking Mobile App',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#d9d9d9]',
  },
  {
    category: 'Illustration',
    title: 'PICKLE CARTOON',
    href: '/projects',
    imageSrc: '/images/cartoon.jpg',
    imageAlt: 'Pickle Cartoon',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#f5f0d8]',
  },
  {
    category: 'Branding',
    title: 'EMPHERIA AGRICULTURE',
    href: '/projects',
    imageSrc: '/images/womanglasses.png',
    imageAlt: 'Empheria Agriculture Branding',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#c8b49a]',
  },
  {
    category: 'Web Design',
    title: 'SECURED FINANCE',
    href: '/projects',
    imageSrc: '/images/webdesign.png',
    imageAlt: 'Secured Finance',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#8a8a7a]',
  },
  {
    category: 'Branding',
    title: 'EMPHERIA AGRICULTURE',
    href: '/projects',
    imageSrc: '/images/lumina.png',
    imageAlt: 'Lumina Branding',
    imageClassName: 'object-cover object-center',
    bgClassName: 'bg-[#2a4a3a]',
  },
]